language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy

# command to install dependencies
install:
    - pip install tox

script:
    - printf "[build_ext]\nportage-ext-modules=true" >> setup.cfg
    - find . -type f -exec
          sed -e "s|@PORTAGE_EPREFIX@||"
              -e "s|@PORTAGE_BASE@|${PWD}|"
              -e "s|@PORTAGE_MV@|$(type -P mv)|"
              -e "s|@PORTAGE_BASH@|$(type -P bash)|"
              -e "s|@PREFIX_PORTAGE_PYTHON@|$(type -P python)|"
              -e "s|@DEFAULT_PATH@|/usr/bin:/bin|"
              -e "s|@EXTRA_PATH@|/usr/sbin:/sbin|"
              -e "s|@portagegroup@|$(id -gn)|"
              -e "s|@portageuser@|$(id -un)|"
              -e "s|@rootuser@|$(id -un)|"
              -e "s|@rootuid@|$(id -u)|"
              -e "s|@rootgid@|$(id -g)|"
              -e "s|@sysconfdir@|/etc|"
              -i '{}' +
    - ./setup.py test
    - ./setup.py install --root=/tmp/install-root
    - if [[ ${TRAVIS_PYTHON_VERSION} == ?.? ]]; then
        tox -e py${TRAVIS_PYTHON_VERSION/./};
      else
        tox -e ${TRAVIS_PYTHON_VERSION};
      fi
